version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "stockfish"
      - dependency-name: "react"
      - dependency-name: "react-dom"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
